Username: tosone
Repo: release
Branch: master
Rewrite: true
Draft: false
Prerelease: false
Runtime:
  Timeout: 10
  Debug: true
Release:
  Files:
    - release/*
  Compress: true
  CompressWith:
    - README.md
    - .release.yml
