language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
before_install:
  - sudo apt-get -qq update
before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - make lint
  - make
deploy:
  provider: script
  skip_cleanup: true
  script:
    - make release && sudo mv release/release /usr/bin && release create
  on:
    tags: true
